name: Publish to pub.dev

on:
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  merge_job:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install dependencies
        run: npm ci
        working-directory: ./.github/scripts/release
      - name: Git config
        run: |
          git config --local user.email 'hello@rive.app'
          git config --local user.name ${{ github.actor }}
      - name: Release
        run: ./release.sh
        working-directory: ./.github/scripts/release
        env:
          GITHUB_AUTHOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.RIVE_REPO_PAT }}
